name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flags:
          - "-Xms256m -Xmx512m"             # Taille initiale et maximale du tas (mémoire)
          - "-XX:+UseSerialGC"               # Utilise le ramasse-miettes Serial
          - "-XX:+TieredCompilation"         # Active la compilation par niveaux
          - "-XX:+HeapDumpOnOutOfMemoryError" # Dump mémoire en cas d'erreur OOM
          - "-Dfile.encoding=UTF-8"          # Définit l'encodage des fichiers

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven and Flags
      run: |
        echo "Running build with flags: ${{ matrix.flags }}"
        ./mvnw -B clean verify jacoco:report -DargLine="${{ matrix.flags }}"
      timeout-minutes: 15

    - name: Get JaCoCo Coverage
      id: coverage
      run: |
        if [ ! -f "target/site/jacoco/jacoco.csv" ]; then
          echo "Error: jacoco.csv file not found."
          exit 1
        fi
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
        echo "Extracted coverage: $coverage"
        if [ -z "$coverage" ] || ! [[ "$coverage" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
          echo "Error: Coverage is not a valid number."
          exit 1
        fi
        echo "COVERAGE=$coverage" >> $GITHUB_ENV

    - name: Fail if coverage has not improved
      run: |
        coverage=$COVERAGE
        threshold=24.46
        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
          echo "Coverage is not improved."
          exit 1
        else
          echo "New coverage: $coverage%. Coverage is improved!"
        fi

    - name: Upload Coverage Report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: "Coverage Report - Flags ${{ matrix.flags }}"
        path: target/site/jacoco
